# Generated by Django 4.2.9 on 2024-02-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_notification_periodicallynotification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="periodicallynotificationshots",
            name="notification",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="is_joined",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PeriodicallyNotification",
        ),
        migrations.DeleteModel(
            name="PeriodicallyNotificationShots",
        ),
    ]
