# Generated by Django 4.2.9 on 2024-03-05 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_periodicallynotificationshots_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="users.telegramuser",
            ),
        ),
    ]
